Add bookings
Tikkimik/java-shareit pull request #3
Opened 2022-10-21 03:06 UTC by Tikkimik

2022-10-22 10:34 UTC, alexache requested changes

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Long itemId;
Здесь и далее во всех полях класса, где есть внешние ключи. желательно получать объекты соответствующих классов, а не просто айди - через @JoinColumn и @ManyToOne аннотаций

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private Long item;
Повторный комментарий про @JoinColumn и @ManyToOne аннотации

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner;
Повторный комментарий про @JoinColumn и @ManyToOne аннотации

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingService.getAllBookings(userId, state);
state можно бы тоже обернуть в енам, BookingState, например

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private String text;
В эти новые классы тоже можно добавлять валидации

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void checkBookingTimings(BookingDto bookingDto) {
Такие валидации (не зависящие от БД) лучше делать в контроллере или на ДТО

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Autowired
Если есть @RequiredArgConstructor, то зачем еще и @Autowired? Лучше придерживаться чего-то одного

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final ItemMapper itemMapper;
Зачем хранить поля классов, в которых только статичные методы?

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName().isEmpty())
Такие проверки лучше иметь в контроллдере или дто

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +//        List<CommentDtoWithAuthorAndItem> commentDtoWithAuthorAndItemList = commentRepository.findAllByItem(item.getId())
Закомментированный код должен быть удален

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    User getUserByEmail(String email);
В таких методах лучше подходит Optional<User> в качестве возвращаемого типа, возвращаясь к тренировкам с функциональным стилем

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private final UserMapper userMapper;
Тоже лишнее

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    @Autowired
И тоже смесь @RequiredArgsConstructor vs @Autowired

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return userMapper.toUserDto(userRepository.getUserByEmail(userDto.getEmail()));
Для чего делать лишний гет к базе? Метод save возвращает нужный объект

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        UserDto userFromStorage = getUser(userId);
Очень какие-то сложные манипуляции с объектами. Можно взять объект User у репозитория, и с ним работать. Ни к чему дто -> неДто по несколько раз делать без лишней надобности

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        userRepository.deleteAllById(List.of(userId));
Почему не deleteById?

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void checkUserEmail(UserDto userDto) throws IncorrectParameterException {
Такие проверки лучше делать ближе к контроллеру

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private final BookingMapper bookingMapper;
Лишние поля

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemRepository.getReferenceById(bookingDto.getItemId());
Почему не findById?

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemRepository.getReferenceById(itemId);
Опять же непонятно, для чего не findById, и зачем второй раз запрашивать тот же объект Item. Например, в методе getBooking объект из репозитория уже был

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!bookingRepository.existsById(bookingId))
Опять же еще один вызов в БД. В некоторых методах таких вызовов наберется по 2-3. Лучше в самом начале просто получать объект вещи, и работать с ним, чем делать много запросов

2022-10-22 10:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        for (Item i : items) {
Очень нехороший способ в циклах ходить в БД. БД на то и имеет SQL, чтобы делать гибкие условия фильтрации и обработки. Тут лучше делать абсолютно разные запросы через  bookingRepository (можно писать запросы с join на owner и таблицу Item)

2022-10-22 20:51 UTC, Tikkimik commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Autowired
Спасибо! Создание всех бинов в конструкторе помогло избавиться от проблемы (в постмане уезжало время при проверках).

2022-10-24 21:13 UTC, alexache approved these changes

2022-10-24 21:13 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +    CANCELED,
Это объединение двух разных сущностей в один енам - плохая практика, и не понятно, в чем преимущество?

2022-10-27 20:56 UTC, merged